# Generated by Django 3.2.25 on 2024-11-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advuser',
            old_name='send_message',
            new_name='send_messages',
        ),
    ]
