# Generated by Django 3.2.25 on 2024-11-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designapp', '0002_auto_20241126_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='time',
            new_name='created_at',
        ),
    ]
