# Generated by Django 3.2.25 on 2024-11-30 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designapp', '0003_application_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='district',
            field=models.CharField(choices=[('k', 'Кировский'), ('l', 'Ленинский'), ('o', 'Октябрьский')], default='l', help_text='Choose a district', max_length=1),
        ),
        migrations.AddField(
            model_name='advuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
